### ISSUE TITLE
+2 Card not working

### ISSUE THREAD

**Issue by rinvii** [n8hopp/GameStateInClass#5]
When a previous player plays a +2, and it is your turn, and you have one card, you can don't need to draw two times. You can just immediately win.

![image](https://user-images.githubusercontent.com/76126859/202027321-3c3abe24-66f7-4140-bc12-4ad575eb94e6.jpeg)

![image](https://user-images.githubusercontent.com/76126859/202027347-97380567-809b-43ca-a3ef-0214a844c478.jpeg)

**Comment by millerl23** [comment]
We have not been able to replicate this error. We believe that the issue is in the lack of clarity with the blue arrow not pausing when a player places a draw two card. We believe that the top computer played the +2, the 2 cards were automatically added to the right computer's hand and then it progressed to the human player's turn. This all is fine and dandy but we need the blue arrow to pause on the player drawing two cards rather than everything happening at once. Essentially then, this ticket will be close once the turn arrow successfully pauses on any skipping card action.

**Comment by millerl23** [comment]
We have added an action text functionality that displays in the center of the screen detailing the last action that occurred. We believe that this will be sufficient for clearing up the confusion of the blue arrow not stopping on a skipping action. We will find out from the audience whether that is true or not during beta testing.
